httpbin:
  ribbon:
    listOfServers: github.com:443
logging:
  level:
    org:
      apache: DEBUG
zuul:
  routes:
    httpbin:
      path: /github/**
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 130000
  ConnectTimeout: 140000
  IsSecure: true

